Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_stream
KerasH5: keras/KERAS_conv2d_model_weights.h5
KerasJson: keras/KERAS_conv2d_model.json
OutputDir: stream_test
ProjectName: myproject
Stamp: c3FfbE0E
XilinxPart: xcku115-flvb2104-2-i
